query RDBRun($id: Int, $runNo: Int) {
  rdb {
    run(id: $id, runNo: $runNo) {
      id
      runNo
      state
      startedAt
      endedAt
      script
      exception
      traces {
        pageInfo {
          startCursor
          endCursor
        }
        totalCount
        edges {
          cursor
          node {
            id
            runNo
            traceNo
          }
        }
      }
      prompts {
        pageInfo {
          startCursor
          endCursor
        }
        totalCount
        edges {
          cursor
          node {
            id
            runNo
            promptNo
          }
        }
      }
      stdouts {
        pageInfo {
          startCursor
          endCursor
        }
        totalCount
        edges {
          cursor
          node {
            id
            runNo
            writtenAt
          }
        }
      }
    }
  }
}
